# Generated by Django 2.0.7 on 2018-07-25 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sucesuview', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='data_evento',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='imagem_evento',
            new_name='imagem',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='local_evento',
            new_name='local',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='sobre_evento',
            new_name='sobre',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='titulo_evento',
            new_name='titulo',
        ),
    ]
