# Generated by Django 2.0.7 on 2018-07-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucesuview', '0003_auto_20180725_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='hora',
            field=models.TimeField(default=None),
        ),
    ]
