# Generated by Django 2.0.7 on 2018-07-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucesuview', '0005_auto_20180726_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assossiados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('imagem', models.ImageField(upload_to='images/associados/%Y-%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Parceiros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('imagem', models.ImageField(upload_to='images/parceiros/%Y-%m/%d')),
            ],
        ),
    ]
