# Generated by Django 2.0.7 on 2018-07-30 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sucesuview', '0006_assossiados_parceiros'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assossiados',
            new_name='Assossiado',
        ),
        migrations.RenameModel(
            old_name='Parceiros',
            new_name='Parceiro',
        ),
    ]
