# Generated by Django 2.0.7 on 2018-07-30 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sucesuview', '0007_auto_20180730_0923'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assossiado',
            new_name='Associado',
        ),
    ]
